CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255),
    senha_hash VARCHAR(255),
    senioridade_alvo VARCHAR(255),
    github VARCHAR(255),
    linkedin VARCHAR(255),
    foto_perfil VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS stacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_coleta TIMESTAMP,
    descricao TEXT,
    empresa VARCHAR(255),
    fonte VARCHAR(255),
    link_original VARCHAR(255),
    senioridade VARCHAR(255) CHECK (senioridade IN ('ESTAGIARIO','JUNIOR','PLENO','SENIOR','NAO_INFORMADO')),
    titulo VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_interacao TIMESTAMP,
    status VARCHAR(255),
    user_id BIGINT REFERENCES users(id),
    job_id BIGINT REFERENCES jobs(id)
);

CREATE TABLE IF NOT EXISTS job_stacks (
    job_id   BIGINT NOT NULL REFERENCES jobs(id),
    stack_id BIGINT NOT NULL REFERENCES stacks(id),
    PRIMARY KEY (job_id, stack_id)
);

CREATE TABLE IF NOT EXISTS user_stacks (
    user_id  BIGINT NOT NULL REFERENCES users(id),
    stack_id BIGINT NOT NULL REFERENCES stacks(id),
    PRIMARY KEY (user_id, stack_id)
);

CREATE TABLE IF NOT EXISTS user_stacks_preferidas (
    user_id  BIGINT NOT NULL REFERENCES users(id),
    stack_id BIGINT NOT NULL REFERENCES stacks(id),
    PRIMARY KEY (user_id, stack_id)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         BIGSERIAL PRIMARY KEY,
    token      VARCHAR(36)  NOT NULL UNIQUE,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMP    NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE
);

INSERT INTO stacks (nome) VALUES
  ('Java'),('Spring Boot'),('Python'),('.NET'),('Node.js'),('PHP'),
  ('Laravel'),('Golang'),('Ruby on Rails'),('Kotlin'),('C++'),('Django'),
  ('FastAPI'),('NestJS'),('JavaScript'),('TypeScript'),('React'),('Angular'),
  ('Vue.js'),('Next.js'),('Tailwind CSS'),('Flutter'),('React Native'),
  ('Android SDK'),('PostgreSQL'),('MySQL'),('Oracle Database'),('SQL Server'),
  ('MongoDB'),('Redis'),('Elasticsearch'),('Firebase'),('AWS'),('Azure'),
  ('Google Cloud Platform'),('Docker'),('Kubernetes'),('Terraform'),('Jenkins'),
  ('GitHub Actions'),('GitLab CI'),('GraphQL'),('RabbitMQ'),('Apache Kafka'),('Selenium')
ON CONFLICT (nome) DO NOTHING;
